### ISSUE TITLE
Adding multiple backends concurrently fail

### ISSUE THREAD

**Issue by mathianasj** [zevenet/zlb#65] opened 2020-03-18 17:35 UTC
If I try to create two backends at the same time against L4XNAT farm only one backend gets created.

**Comment by nevola** [comment] 2020-03-18 17:37
Hi Mathias, please check the syslog file looking for any raised error. Thanks!

**Comment by adanmarin-zevenet** [comment] 2020-05-13 12:36
We are not able to reproduce this.

Please, try to upgrade to the latest version and confirm if it fixes the problem.

**Comment by adanmarin-zevenet** [comment] 2020-06-08 07:42
Good day,
We will proceed to close this ticket after a while without updated information.

**Closed as completed** 2020-06-08 07:43 UTC
Labels: pending feedback
